# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_name', models.TextField(default='')),
                ('street_address', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('zip', models.TextField(default='')),
                ('contact_person', models.TextField(default='')),
                ('contact_phone', models.TextField(default='')),
                ('contact_email', models.TextField(default='')),
                ('program', models.TextField(default='')),
                ('po', models.TextField(default='')),
                ('contact_name', models.TextField(default='')),
                ('job_title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('so_1', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abet_form.User'),
        ),
    ]
