# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abet_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.TextField(default='')),
                ('po', models.TextField(default='')),
                ('contact_name', models.TextField(default='')),
                ('job_title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('so_1', models.BooleanField(default=False)),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abet_form.Abet_Form')),
            ],
        ),
    ]
