# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('abet_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
