# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abet_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='list',
        ),
        migrations.DeleteModel(
            name='Abet_Form',
        ),
    ]
