# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abet_form', '0002_auto_20181111_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_person',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='street_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='zip',
            field=models.TextField(default=''),
        ),
    ]
