# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abet_form', '0003_auto_20181111_1517'),
        ('abet_form', '0003_auto_20181112_2215'),
    ]

    operations = [
    ]
