# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abet_form', '0004_merge_20181112_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='abet_form',
        ),
        migrations.DeleteModel(
            name='Abet_Form',
        ),
    ]
